spring.application.name=pmh3512-1

server.port=80

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.zvbgzlbhwjxrtmqdvrjw
spring.datasource.password=UQBv8xlW0QMdnxeN

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.winter.jisu
